language: python
python:
- 3.7
dist: xenial
sudo: true
cache: pip
install:
- pip install -U pip
- pip install codecov
- pip install -r requirements.txt
script:
- coverage run -m doctest chain/utils/elliptic.py
- coverage run -m unittest discover .
after_success:
- codecov
